language: generic
sudo: false

env:
  matrix:
    - EMACS_VERSION=26.1
    - EMACS_VERSION=25.3
    - EMACS_VERSION=24.5

# matrix:
#   allow_failures:
#     - env: EMACS_VERSION=26-pretest

before_install:
  - git clone --depth=1 https://github.com/rejeep/evm.git ./.evm
  - ./.evm/bin/evm config path /tmp
  - ./.evm/bin/evm install emacs-$EMACS_VERSION-travis --use
  - ./.evm/bin/emacs --version
  - if [[ "$EMACS_VERSION" == 24.5 ]]; then curl "http://git.savannah.gnu.org/cgit/emacs/elpa.git/plain/packages/cl-generic/cl-generic.el?id=a1cdea05e8cbfe15ba075c64417db20b814e48e8" >cl-generic.el; fi

script:
  make test EMACS=$PWD/.evm/bin/emacs
